### ISSUE TITLE
Multiple examples under example

### ISSUE THREAD

**Issue by mcupak** [ga4gh-beacon/specification#165]
For some properties, there are multiple examples under a single `example` field, which is misleading. `examples` should be used instead.

**Comment by mcupak** [comment]
I'm reopening this issue as this wasn't solved correctly in #189. Examples should be listed separately, not as a string containing "or". Such a string is still just a single example.

**Comment by mcupak** [comment]
To clarify, it should look like this:

```yaml
examples:
  foobar:
    value:
      id: foo
      name: bar
```

**Comment by mcupak** [comment]
This is actually a blocker for the release - the current content is not valid and [breaks the build](https://travis-ci.org/ga4gh-beacon/specification/builds/394125782).

**Comment by sdelatorrep** [comment]
As noted by @juhtornr , `examples`cannot be used for schemas and properties (see [here](https://swagger.io/docs/specification/adding-examples/)). So, we can fix the examples provided in the `variantType `parameter but the others cases will remain as they are (`example` with multiple examples specified in the string).

**Comment by sdelatorrep** [comment]
Hi guys,
It seems that swagger-ui cannot render `examples` (see [this](https://github.com/swagger-api/swagger-ui/issues/2651)). I suggest keeping the "Examples" within the description string so they can still be seen in the UI.
```yaml
        - name: variantType
          description: |
            The `variantType` is used to denote e.g. structural variants. 
            
            Examples:
            * DUP: duplication of sequence following `start`; not necessarily in
            situ
            * DEL: deletion of sequence following `start`
            
            Optional: either `alternateBases` or `variantType` is required.
          in: query
          required: false
          schema:
            type: string
          examples:
            dup:
              value: DUP
              summary: duplication of sequence following `start`; not necessarily in
            del:
              value: DEL
              summary: deletion of sequence following `start`
```
WDYT?
