### ISSUE TITLE
apiVersion vs version

### ISSUE THREAD

**Issue by teemukataja** [ga4gh-beacon/specification#229]
In the `Beacon` model of the specification, there are two _version_ keys, apiVersion and version. The keys' descriptions are the following:
```
        apiVersion:
          type: string
          description: Version of the API provided by the beacon.
          example: v0.3
```
```
        version:
          type: string
          description: Version of the beacon.
          example: v0.1
```
What is the difference between the two, and their use cases?
