### ISSUE TITLE
Type of start and end coordinates

### ISSUE THREAD

**Issue by cyenyxe** [ga4gh-beacon/specification#289]
Parameters `startMin`,`startMax`,`end`, `endMin`,`endMax` are declared as being of type `Integer`, but the code (at least in Java) that results in the `QueryApiController` and  `QueryApi` classes requires them to be `Long`. In fairness, it could be the case that a coordinate exceeds the limit of an `Integer`, so changing the declaration to match that type would be ideal.

**Comment by blankdots** [comment]
Just a small note as there are other implementations in other languages, please keep in mind the specification should not be language dependent. 

Also OpenAPI best options would be `number` if integer would not be used as per available data types: https://swagger.io/docs/specification/data-models/data-types/ the same would be if used in JSON schema.

**Comment by cyenyxe** [comment]
I would actually favor type `integer` with format `int64`. Not so much because of the Java implementation, which only helped us to notice the issue, but because we would like to adopt the Beacon for non-human species and in some of those an `int32` is definitely not enough.

**Comment by mbaudis** [comment]
@cyenyxe I agree w/ @blankdots, but also support the addition of the `int64` as format. So @sdelatorrep for picking this up?

**Comment by sdelatorrep** [comment]
Hi! The definition of `start`, `end`, `startMin`, `startMax`, `endMin` and `endMax` is already an `integer` with format `int64` so, if I didn't misunderstand the problem, no change in the spec is needed. E.g.
```
        - name: start
          description: (...)
          in: query
          required: false
          schema:
            type: integer
            format: int64
            minimum: 0
```
