### ISSUE TITLE
Either CC or ADA-M should be provided

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification#293]
Currently, both fields are mandatory, but they should be optional (well, if the user is setting the `dataUseConditions` field they should provide at least one of these two but I'm not sure it this can be specified with OpenAPI):
```
    DataUseConditions:
      type: object
      required:
        - consentCodeDataUse
        - adamDataUse
      description: Data use conditions ruling this dataset.
```
